// export const data = {{"id":'1',"nama_kriteria":"Boehm-Rath","bobot":1,"sifat":false},
// {"id":2,"nama_kriteria":"Jenkins LLC","bobot":10,"sifat":true},
// {"id":3,"nama_kriteria":"Dare-Considine","bobot":9,"sifat":true},
// {"id":4,"nama_kriteria":"Mohr-Langosh","bobot":4,"sifat":true},
// {"id":5,"nama_kriteria":"Boyer-Boyle","bobot":5,"sifat":false},
// {"id":6,"nama_kriteria":"Ruecker-Berge","bobot":3,"sifat":true},
// {"id":7,"nama_kriteria":"Kozey, Ernser and Keebler","bobot":10,"sifat":true},
// {"id":8,"nama_kriteria":"McKenzie, Stoltenberg and Maggio","bobot":10,"sifat":true},
// {"id":9,"nama_kriteria":"Mertz Inc","bobot":5,"sifat":false},
// {"id":10,"nama_kriteria":"Shields-Fahey","bobot":9,"sifat":false}}
